name: randomuser
options:
  bundleIdPrefix: es.com.jano.randomuser
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "14.5"

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    DEVELOPMENT_TEAM: PPSF6CNP8Q

packages:

  Log:
    url: git@github.com:janodev/log.git
    from: 1.0.0

  Networking:
    path: ..

targets:

  RandomUser:
    dependencies:
      - package: Networking
      - package: Log
    platform: iOS
    settings:
      CURRENT_PROJECT_VERSION: 1
      DEVELOPMENT_TEAM: PPSF6CNP8Q
      INFOPLIST_FILE: targets/main/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 14.5
      MARKETING_VERSION: 1.0.0
      PRODUCT_BUNDLE_IDENTIFIER: es.com.jano.randomuser
      PRODUCT_NAME: RandomUser
    scheme:
      testTargets:
        - RandomUserTests
    sources:
      - sources/main
      - targets/main/Info.plist
    type: framework

  RandomUserTests:
    dependencies:
      - target: RandomUser
    platform: iOS
    settings:
      DEVELOPMENT_TEAM: PPSF6CNP8Q
      INFOPLIST_FILE: targets/tests/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 14.5
      PRODUCT_BUNDLE_IDENTIFIER: "es.com.jano.randomuser.tests"
    sources:
      - sources/tests
      - targets/tests/Info.plist
    type: bundle.unit-test
