name: RandomUser
options:
  bundleIdPrefix: es.com.jano.randomuser
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "14.5"

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    DEVELOPMENT_TEAM: PPSF6CNP8Q

packages:

  LogDynamic:
    url: git@github.com:janodev/log.git
    from: 1.0.0

  NetworkingDynamic:
    path: ..

targets:

  RandomUserApi:
    dependencies:
      - package: LogDynamic
      - package: NetworkingDynamic
    platform: iOS
    settings:
      CURRENT_PROJECT_VERSION: 1
      DEVELOPMENT_TEAM: PPSF6CNP8Q
      INFOPLIST_FILE: targets/main/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 14.5
      MARKETING_VERSION: 1.0.0
      PRODUCT_BUNDLE_IDENTIFIER: es.com.jano.randomuser
      PRODUCT_NAME: RandomUserApi
    scheme:
      testTargets:
        - RandomUserApiTests
    sources:
      - sources/main
      - targets/main/Info.plist
    type: framework

  RandomUserApiTests:
    dependencies:
      - target: RandomUserApi
    platform: iOS
    settings:
      DEVELOPMENT_TEAM: PPSF6CNP8Q
      INFOPLIST_FILE: targets/tests/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 14.5
      PRODUCT_BUNDLE_IDENTIFIER: "es.com.jano.randomuser.tests"
    sources:
      - sources/tests
      - targets/tests/Info.plist
    type: bundle.unit-test
